version: '3.7'
services:

    # https://hub.docker.com/r/markusmcnugen/qbittorrentvpn/
    qbittorrent:
        container_name: qbittorrent
        image: markusmcnugen/qbittorrentvpn:latest
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            #WEBUI_PORT_ENV: '6880'
            LAN_NETWORK: '192.168.1.0/24'
            VPN_ENABLED: 'yes'
            #INCOMING_PORT_ENV: '6881'
        networks:
            - traefik
        volumes:
            - '${CONFIG_DIR}/qbittorrent:/config'
            - '${DOWNLOADS_DIR}:/downloads'
        ports:
            - '6881:8999'
            - '6881:8999/udp'
            - '6880:8080'
        labels:
            traefik.enable: true
            traefik.port: 6880
            traefik.docker.network: traefik
            traefik.http.routers.qbittorrent.entrypoints: https
            traefik.http.routers.qbittorrent.tls.certresolver: le
            traefik.http.routers.qbittorrent.rule: Host(`qbit.${ACME_DOMAIN}`)
    
        # https://hub.docker.com/r/linuxserver/ombi/
    ombi:
        container_name: ombi
        image: linuxserver/ombi:latest
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - traefik
        volumes:
            - '${CONFIG_DIR}/ombi:/config'
            - '${DOWNLOADS_DIR}:/downloads'
        ports:
            - '3579:3579'
        labels:
            traefik.enable: true
            traefik.port: 3579
            traefik.docker.network: traefik
            traefik.http.routers.ombi.entrypoints: https
            traefik.http.routers.ombi.tls.certresolver: le
            traefik.http.routers.ombi.rule: Host(`ombi.${ACME_DOMAIN}`)

networks:
    traefik:
        name: traefik
        attachable: true