version: '3.7'
services:

    # https://hub.docker.com/r/binhex/arch-delugevpn/
    deluge:
        container_name: deluge
        image: binhex/arch-delugevpn:latest
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            LAN_NETWORK: '${LAN_NETWORK}'
            VPN_ENABLED: 'yes'
            INCOMING_PORT: '6881'
            NAME_SERVERS: '${NAME_SERVERS}'
            STRICT_PORT_FORWARD: 'yes'
            ENABLE_PRIVOXY: 'no'
            DELUGE_DAEMON_LOG_LEVEL: 'info'
            DELUGE_WEB_LOG_LEVEL: 'info'
            DEBUG: 'false'
        networks:
            - traefik
        volumes:
            - '${CONFIG_DIR}/deluge:/config'
            - '${DOWNLOADS_DIR}:/data'
            - '/etc/localtime:/etc/localtime:ro'
        ports:
            - '8112:8112'
            - '58846:58846'
            - '58946:58946'
        labels:
            traefik.enable: true
            traefik.port: 8122
            traefik.docker.network: traefik
            traefik.http.routers.deluge.entrypoints: https
            traefik.http.routers.deluge.tls.certresolver: le
            traefik.http.routers.deluge.rule: Host(`qbit.${ACME_DOMAIN}`)
    
        # https://hub.docker.com/r/linuxserver/ombi/
    ombi:
        container_name: ombi
        image: linuxserver/ombi:latest
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - traefik
        volumes:
            - '${CONFIG_DIR}/ombi:/config'
            - '${DOWNLOADS_DIR}:/downloads'
        ports:
            - '3579:3579'
        labels:
            traefik.enable: true
            traefik.port: 3579
            traefik.docker.network: traefik
            traefik.http.routers.ombi.entrypoints: https
            traefik.http.routers.ombi.tls.certresolver: le
            traefik.http.routers.ombi.rule: Host(`ombi.${ACME_DOMAIN}`)

networks:
    traefik:
        name: traefik
        attachable: true