version: '3.7'
services:

    # https://hub.docker.com/r/linuxserver/sonarr/
    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr:latest
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - internal
        volumes:
            - '${CONFIG_DIR}/sonarr:/config'
            - '${DOWNLOADS_DIR}:/downloads'
            - '${MEDIA_DIR}:/media'
        ports:
            - '8989:8989/tcp'
        labels:
            traefik.enable: true
            traefik.port: 8989
            traefik.docker.network: internal
            traefik.http.routers.sonarr.entrypoints: http
            # traefik.http.routers.sonarr.tls.certresolver: le
            traefik.http.routers.sonarr.rule: Host(`sonarr.${LOCAL_DOMAIN}`)


    # https://hub.docker.com/r/linuxserver/radarr/
    radarr:
        container_name: radarr
        image: linuxserver/radarr:latest
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - internal
        volumes:
            - '${CONFIG_DIR}/radarr:/config'
            - '${DOWNLOADS_DIR}:/downloads'
            - '${MEDIA_DIR}:/media'
        ports:
            - '7878:7878/tcp'
        labels:
            traefik.enable: true
            traefik.port: 7878
            traefik.docker.network: internal
            traefik.http.routers.radarr.entrypoints: http
            # traefik.http.routers.radarr.tls.certresolver: le
            # traefik.http.routers.radarr.middlewares: secureheaders 
            traefik.http.routers.radarr.rule: Host(`radarr.${LOCAL_DOMAIN}`)
    
    # https://hub.docker.com/r/linuxserver/hydra2/
    hydra:
        container_name: hydra
        image: linuxserver/hydra2:latest
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - internal
        volumes:
            - '${CONFIG_DIR}/hydra:/config'
            - '${DOWNLOADS_DIR}:/downloads'
        ports:
            - '5076:5076/tcp'
        labels:
            traefik.enable: true
            traefik.port: 5076
            traefik.docker.network: internal
            traefik.http.routers.hydra.entrypoints: http
            # traefik.http.routers.hydra.tls.certresolver: le
            # traefik.http.routers.hydra.middlewares: secureheaders 
            traefik.http.routers.hydra.rule: Host(`hydra.${LOCAL_DOMAIN}`)

networks:
    internal:
        name: internal
        attachable: true