################################################################
# Global configuration
################################################################
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

# ###############################################################
# Providers configuration
# ###############################################################
[providers.file]
  directory = "/config/"
  watch = true
################################################################
# Entrypoints configuration
################################################################
[entryPoints]
  [entryPoints.http]
    address = ":80"
    # [entryPoints.http.http.redirections]
    #   [entryPoints.http.http.redirections.entryPoint]
    #     to = "https"
    #     scheme = "https"

  [entryPoints.https]
    address = ":443"
      [entryPoints.https.forwardedHeaders]
      # Trust Headers from CloudFlare Proxy IPs to enable whitelisting
        trustedIPs = ["173.245.48.0/20",
                      "103.21.244.0/22",
                      "103.22.200.0/22",
                      "103.31.4.0/22",
                      "141.101.64.0/18",
                      "108.162.192.0/18",
                      "190.93.240.0/20",
                      "188.114.96.0/20",
                      "197.234.240.0/22",
                      "198.41.128.0/17",
                      "162.158.0.0/15",
                      "104.16.0.0/12",
                      "172.64.0.0/13",
                      "131.0.72.0/22"]

  [entryPoints.metrics]
    address = ":8082"

################################################################
# Traefik logs configuration
################################################################
# Enabled by default and log to stdout
[log]

  # Log level
  level = "INFO"

  # Sets the filepath for the traefik log. If not specified, stdout will be used.
  # Intermediate directories are created if necessary.
  #
  # Optional
  # Default: os.Stdout
  #
  # filePath = "log/traefik.log"

  # Format is either "json" or "common".
  format = "common"

################################################################
# Access logs configuration
################################################################
[accessLog]

  # Sets the file path for the access log. If not specified, stdout will be used.
  # Intermediate directories are created if necessary.
  #
  # Optional
  # Default: os.Stdout
  #
  # filePath = "/path/to/log/log.txt"

  # Format is either "json" or "common".
  format = "common"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]
  # Enabled Dashboard
  dashboard = true

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

################################################################
# Router configuration
################################################################
[serversTransport]
  insecureSkipVerify = false

################################################################
# Middleware configuration
################################################################
[http.routers]
  [http.routers.http]
    middlewares = 'redirectscheme'
    entryPoints = 'http'

[http.middlewares]
  [http.middlewares.secureheaders]
    [http.middlewares.secureheaders.headers]
      stsSeconds = 15552000
      framedeny = true
      sslForceHost = true
      sslRedirect = true
      stsIncludeSubdomains = true
      browserXssFilter = true
      contentTypeNosniff = true
      forceSTSHeader = true
      stsPreload = true
      customFrameOptionsValue = 'SAMEORIGIN'
    
    [http.middlewares.secureheaders.headers.customResponseHeaders]
      X-Robots-Tag = 'none'
      server = ''

  [http.middlewares.internal]
    [http.middlewares.internal.ipWhiteList]
        sourceRange = ["192.168.0.0/24"]

  [http.middlewares.redirectscheme]
    [http.middlewares.redirectscheme.redirectscheme]
      scheme= 'https'

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[providers.docker]
  # Expose containers by default in traefik
  exposedByDefault = false
  # Name of the network Containers will connect to
  network = 'external'

  # Enable ACME (Let's Encrypt): automatic SSL.
[certificatesResolvers.le.acme]
  # File or key used for certificates storage.
  storage = "/cert/acme.json"

  #Choose Type of Key used for Certificate
  keyType = 'RSA4096'

  # Choose the Certificate Authority Server to be used for Let's Encrypt
  caServer = "https://acme-v02.api.letsencrypt.org/directory"

# Use a DNS-01 ACME challenge rather than HTTP-01 challenge.
# Note: mandatory for wildcard certificate generation.

[certificatesResolvers.le.acme.dnsChallenge]

  # DNS provider used.
  provider = "cloudflare"

  # By default, the provider will verify the TXT DNS challenge record before letting ACME verify.
  # If delayBeforeCheck is greater than zero, this check is delayed for the configured duration in seconds.
  # Useful if internal networks block external DNS queries.
  delayBeforeCheck = 0

  # DNS Resolvers
  # Required for Cloudflare
  resolvers = ["1.1.1.1:53", "1.0.0.1:53"]

# Metrics definition
[metrics]
  # To enable Traefik to export internal metrics to Prometheus
  [metrics.prometheus]

    # Name of the related entry point
    entryPoint = "traefik"

    # Buckets for latency metrics
    buckets = [0.1,0.3,1.2,5.0]

    # Enable metrics on entry points.
    addEntryPointsLabels = true

    # Enable metrics on services.
    addServicesLabels = true
