version: '3.7'
services:

    # https://hub.docker.com/r/linuxserver/nextcloud
    nextcloud:
        container_name: nextcloud
        image: nextcloud
        restart: unless-stopped
        environment: 
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'  
            MYSQL_USER: '${MYSQL_USER}'
            NEXTCLOUD_DATA_DIR: '/data'
        networks:
            - traefik
        ports:
            - '9191:80'
        volumes: 
            - '${CONFIG_DIR}/nextcloud/:/var/www/html/'
            - '${CONFIG_DIR}/nextcloud/apps:/var/www/html/apps'
            - '${NEXTCLOUD_DATA_DIR}:/var/www/html/data/'
        labels:
            traefik.enable: true
            traefik.port: 9191
            traefik.docker.network: traefik
            traefik.http.routers.nextcloud.entrypoints: https
            traefik.http.routers.nextcloud.tls.certresolver: le
            traefik.http.routers.nextcloud.rule: Host(`nextcloud.${ACME_DOMAIN}`)

    # https://hub.docker.com/_/mariadb
    mariadb:
        container_name: mariadb
        image: mariadb
        restart: always
        volumes:
            - '${MARIADB_DIR}/config:/config'
            - '${MARIADB_DIR}/mysql:/var/lib/mysql'
        user: '${PUID}:${PGID}'
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '{MYSQL_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
        networks:
            - traefik        

        labels: 
            traefik.enable: true
            traefik.docker.network: traefik
