version: '3.7'
services:

    # https://hub.docker.com/r/linuxserver/nextcloud
    nextcloud:
        container_name: nextcloud
        image: nextcloud
        restart: unless-stopped
        depends_on:
            - mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${MARIADB_DATABASE}'  
            MYSQL_USER: '${MARIADB_USER}'
            NEXTCLOUD_DATA_DIR: '/data'
        networks:
            - traefik
        ports:
            - '9191:80'
        volumes: 
            - '${CONFIG_DIR}/nextcloud/:/var/www/html/'
            - '${CONFIG_DIR}/nextcloud/apps:/var/www/html/apps'
            - '${NEXTCLOUD_DATA_DIR}:/var/www/html/data/'
        labels:
            traefik.enable: true
            traefik.port: 9191
            traefik.docker.network: traefik
            traefik.http.routers.nextcloud.entrypoints: https
            traefik.http.routers.nextcloud.tls.certresolver: le
            traefik.http.routers.nextcloud.rule: Host(`nextcloud.${DOMAIN}`)

    # https://hub.docker.com/_/mariadb
    mariadb:
        container_name: mariadb
        image: mariadb
        restart: always
        volumes:
            - '${DATABASE_DIR}/mariadb/config:/config'
            - '${DATABASE_DIR}/mariadb/data:/var/lib/mysql'
        user: '${PUID}:${PGID}'
        environment:
            MYSQL_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
            MYSQL_USER: '${MARIADB_USER}'
            MYSQL_PASSWORD: '{MARIADB_PASSWORD}'
            MYSQL_DATABASE: '${MARIADB_DATABASE}'
        networks:
            - traefik        
        labels: 
            traefik.enable: true
            traefik.docker.network: traefik

networks:
    traefik:
        name: traefik
        attachable: true