echo '*****************************'
echo $MYSQL_GRAFANA_DATABASE
echo $MYSQL_GRAFANA_USER
echo $MYSQL_GRAFANA_PASSWORD

mysql -u root -p$MYSQL_ROOT_PASSWORD -e \
"CREATE DATABASE IF NOT EXISTS $MYSQL_GRAFANA_DATABASE;
CREATE USER TO $MYSQL_GRAFANA_USER@'%' IDENTIFIED BY '$MYSQL_GRAFANA_PASSWORD';
GRANT ALL PRIVILEGES ON $MYSQL_GRAFANA_DATABASE.* TO $MYSQL_GRAFANA_USER@'%';"

echo $MYSQL_KEYCLOAK_DATABASE
echo $MYSQL_KEYCLOAK_USER
echo $MYSQL_KEYCLOAK_PASSWORD

mysql -u root -p$MYSQL_ROOT_PASSWORD -e \
"CREATE DATABASE IF NOT EXISTS $MYSQL_KEYCLOAK_DATABASE;
CREATE USER $MYSQL_KEYCLOAK_USER@'%' IDENTIFIED BY '$MYSQL_KEYCLOAK_PASSWORD';
GRANT ALL PRIVILEGES ON $MYSQL_KEYCLOAK_DATABASE.* TO $MYSQL_KEYCLOAK_USER@'%';"

echo '*****************************'