version: '3.7'
services:

    # https://hub.docker.com/r/plexinc/pms-docker
    plex:
        container_name: plex
        image: plexinc/pms-docker:latest
        restart: unless-stopped
        environment:
            PLEX_UID: '${PUID}'
            PLEX_GID: '${PGID}'
            TZ: '${TZ}'
            PLEX_CLAIM: '${PLEX_CLAIM}'
        networks:
            - external
        ports:
            - "32400:32400"
            - "32400:32400/udp"
            - "32469:32469"
            - "32469:32469/udp"
            - "1900:1900/udp"
        volumes:
            - '${CONFIG_DIR}/plex:/config'
            - '${MEDIA_DIR}/tv:/data/tv'
            - '${MEDIA_DIR}/movies:/data/movies'
            - '${MEDIA_DIR}/transcode:/transcode'

    # https://hub.docker.com/r/linuxserver/ombi/
    ombi:
        container_name: ombi
        image: linuxserver/ombi:latest
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - external
            - internal
        volumes:
            - '${CONFIG_DIR}/ombi:/config'
            - '${DOWNLOADS_DIR}:/downloads'
        ports:
            - '3579:3579'

networks:
    external:
        name: external
        attachable: true
    internal:
        name: internal
        attachable: true