version: '3.7'
services:

    # https://hub.docker.com/r/prom/prometheus/
    prometheus:
        container_name: prometheus
        image: linuxserver/ombi:latest
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        command:
            --config.file=/etc/prometheus/prometheus.yml
            --storage.tsdb.path=/data
            --storage.tsdb.retention.time=30d
        volumes:
        - './prometheus.yml:/etc/prometheus/prometheus.yml'
        networks:
            - traefik
        ports:
            - '9090:9090'
        labels:
            traefik.enable: true
            traefik.port: 9090
            traefik.docker.network: traefik
            traefik.http.routers.prometheus.entrypoints: https
            traefik.http.routers.prometheus.tls.certresolver: le
            traefik.http.routers.prometheus.rule: Host(`prometheus.${DOMAIN}`)
    
    # https://hub.docker.com/r/grafana/grafana/
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        depends_on:
            - mysql
        restart: unless-stopped
        environment:
            GF_DATABASE_HOST: 'mysql:3306'
            GF_DATABASE_PASSWORD: '${MYSQL_PASSWORD}'
            GF_DATABASE_USER: '${MYSQL_USER}'
        env_file:
            - ./metrics/config.env
            - ./env
        volumes:
            - './metrics/prometheus.yml:/etc/prometheus/prometheus.yml'
        networks:
            - traefik
        ports:
            - '3000:3000'
        labels:
            traefik.enable: true
            traefik.port: 3000
            traefik.docker.network: traefik
            traefik.http.routers.prometheus.entrypoints: https
            traefik.http.routers.prometheus.tls.certresolver: le
            traefik.http.routers.prometheus.rule: Host(`grafana.${DOMAIN}`)
    
    # https://hub.docker.com/_/mysql
    mysql:
        image: mysql:${MYSQL_VERSION}
        restart: unless-stopped
        volumes:
            - '${DATABASE_DIR}/mysql:/var/lib/mysql:rw'
        environment:
        MYSQL_USER: '${MYSQL_USER}'
        MYSQL_DATABASE: '${MYSQL_DATABASE}'
        MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
        MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        networks:
            - traefik        
        labels: 
            traefik.enable: true
            traefik.docker.network: traefik